src/java/controller/BancaController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import model.TbBanca;
import model.TbCurso;
import model.TbDisciplina;
import model.TbProcesso;
import model.VwBancaDisciplinaCurso;
import service.BancaService;
import service.VwBancaDisciplinaCursoService;
import service.impl.BancaServiceImpl;
import service.impl.VwBancaDisciplinaCursoServiceImpl;



@ManagedBean(name="Banca")
@SessionScoped
public class BancaController extends BasicController {
    
    private TbBanca inserirBanca =new TbBanca();
    private DataModel gridBancas;
    private int idProcesso, idDisciplina, idCurso;
    
    private int idCursoFiltro=0;
    private int idDisciplinaFiltro=0;
    
    //private List<TbBanca> listaBancas = new ArrayList<TbBanca>();
    private List<VwBancaDisciplinaCurso> listaBancas = new ArrayList<VwBancaDisciplinaCurso>();

    
    public BancaController(){
        this.consultaListaBancas();
    }

    public TbBanca getInserirBanca() {
        return inserirBanca;
    }

    public void setInserirBanca(TbBanca inserirBanca) {
        this.inserirBanca = inserirBanca;
    }

    public DataModel getGridBancas() {
        return gridBancas;
    }

    public void setGridBancas(DataModel gridBancas) {
        this.gridBancas = gridBancas;
    }

    public int getIdCurso() {
        return idCurso;
    }

    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

    public int getIdDisciplina() {
        return idDisciplina;
    }

    public void setIdDisciplina(int idDisciplina) {
        this.idDisciplina = idDisciplina;
    }

    public int getIdProcesso() {
        return idProcesso;
    }

    public void setIdProcesso(int idProcesso) {
        this.idProcesso = idProcesso;
    }

    public String insereBanca(){
        BancaService bs = new BancaServiceImpl();
        this.getInserirBanca().setIdCurso(new TbCurso(this.getIdCurso()));
        this.getInserirBanca().setIdDisciplina(new TbDisciplina(this.getIdDisciplina()) );
        this.getInserirBanca().setIdProcesso(new TbProcesso(this.getIdProcesso()));
        TbBanca func = bs.inserir(this.getInserirBanca());
        this.setMensagem("Erro ao inserir banca.");
        if(func!=null){
            this.setMensagem("Banca inserida com sucesso.");
        }
        this.inserirBanca=new TbBanca();
        this.consultaListaBancas();
        return "/view/admin/cadastro/banca.xhtml";
    }


    public List<VwBancaDisciplinaCurso> getListaBanca() {
        //this.consultaListaBancas();
        return listaBancas;
    }

    public void setListaBanca(List<VwBancaDisciplinaCurso> listaFunc) {
        this.listaBancas = listaFunc;
    }


    public String prepararAlterar(){
        this.setMensagem("");
        VwBancaDisciplinaCurso temp = (VwBancaDisciplinaCurso) this.gridBancas.getRowData();
        TbBanca selecionada = (new BancaServiceImpl()).pesquisarPorID(temp.getIdBanca().intValue());
        this.idCurso = selecionada.getIdCurso().getIdCurso();
        this.idDisciplina = selecionada.getIdDisciplina().getIdDisciplina();
        this.idProcesso = selecionada.getIdProcesso().getIdProcesso();
        this.inserirBanca = selecionada;
        return "/view/admin/altera/banca.xhtml";
    }

    public String apaga(){

        BancaService bs = new BancaServiceImpl();
        VwBancaDisciplinaCurso selecionada = (VwBancaDisciplinaCurso) this.gridBancas.getRowData();
        TbBanca banca = bs.pesquisarPorID(selecionada.getIdBanca().intValue());
        bs.apagar(banca);
        this.consultaListaBancas();
        return "/view/admin/cadastro/banca.xhtml";
    }

    public String gravaAlteracao(){
        BancaService bs = new BancaServiceImpl();
        this.inserirBanca.setIdCurso(new TbCurso(this.idCurso));
        this.inserirBanca.setIdDisciplina(new TbDisciplina(this.idDisciplina));
        this.inserirBanca.setIdProcesso(new TbProcesso(this.idProcesso));
        bs.atualizar(this.inserirBanca);
        this.consultaListaBancas();
        this.setMensagem("Banca alterada com sucesso.");
        this.inserirBanca = new TbBanca();
        return "/view/admin/cadastro/banca.xhtml";
    }
    
    private void consultaListaBancas(){
        //BancaService bs=new BancaServiceImpl();
        VwBancaDisciplinaCursoService bs = new VwBancaDisciplinaCursoServiceImpl();
        
        //this.listaBancas =bs.pesquisarTodos();
        this.listaBancas =bs.pesquisarTodosOrdenado();
        this.gridBancas = new ListDataModel(this.listaBancas);
    }
    
    
    public void selecionouDisciplina(){
        this.getListaTodosPorFiltro() ;
    }
    
    /*public void getListaTodasBancasPorDisciplina(){
        BancaService bs = new BancaServiceImpl();
        List<TbBanca> bancaList = null;
           if(this.getDisciplinaSelecionadaFiltro()!= null && this.getDisciplinaSelecionadaFiltro().getIdDisciplina() != 0){
               bancaList = bs.pesquisarPorDisciplina(this.getDisciplinaSelecionadaFiltro().getIdDisciplina());
           }else{
               bancaList = bs.pesquisarTodosOrdenado();
           }
          
            this.gridBancas = new ListDataModel(bancaList);        
    }*/
    
    public void selecionouCurso(){
        this.getListaTodosPorFiltro() ;
    }
    
   /* public void getListaTodasBancasPorCurso(){
        BancaService bs = new BancaServiceImpl();
        List<TbBanca> bancaList = null;
           if(this.getCursoSelecionadoFiltro()!= null && this.getCursoSelecionadoFiltro().getIdCurso() != 0){
               bancaList = bs.pesquisarPorCurso(this.getCursoSelecionadoFiltro().getIdCurso());
           }else{
               bancaList = bs.pesquisarTodosOrdenado();
           }
          
            this.gridBancas = new ListDataModel(bancaList);        
    }*/
    
    public void getListaTodosPorFiltro() {
        VwBancaDisciplinaCursoService bs = new VwBancaDisciplinaCursoServiceImpl();
        List<VwBancaDisciplinaCurso> bancaList = null;
        bancaList = bs.pesquisarPorDisciplinaCurso(this.idDisciplinaFiltro, this.idCursoFiltro);
        this.gridBancas = new ListDataModel(bancaList);
    }

    public int getIdCursoFiltro() {
        return idCursoFiltro;
    }

    public void setIdCursoFiltro(int idCursoFiltro) {
        this.idCursoFiltro = idCursoFiltro;
    }

    public int getIdDisciplinaFiltro() {
        return idDisciplinaFiltro;
    }

    public void setIdDisciplinaFiltro(int idDisciplinaFiltro) {
        this.idDisciplinaFiltro = idDisciplinaFiltro;
    }

    public void selecionaBancaPorProcesso(){

        ColaboradorController cc = ColaboradorController.getInstance();
        
        VwBancaDisciplinaCursoService bs = new VwBancaDisciplinaCursoServiceImpl();
        
        if(cc!=null && cc.getIdProcesso()>0){
            //System.out.println("Here1"+cc.getIdProcesso());
            this.listaBancas =bs.pesquisarTodosOrdenadoPorProcesso(cc.getIdProcesso());
            for(VwBancaDisciplinaCurso atual:listaBancas){
                System.out.println(atual.getNmProcesso()+" - "+atual.getNmBanca());
            }
        }else{
            //System.out.println("Here2");
            this.listaBancas =bs.pesquisarTodosOrdenado();
        }
        this.gridBancas = new ListDataModel(this.listaBancas);
        
    }
    
}

    

src/java/controller/FuncionalidadeController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import model.TbFuncionalidade;
import service.FuncionalidadeService;
import service.impl.FuncionalidadeServiceImpl;


/**
 *
 * @author KAMYLLA
 */

@ManagedBean(name="Funcionalidade")
@SessionScoped
public class FuncionalidadeController extends BasicController {
    
    private TbFuncionalidade inserirFuncionalidade = new TbFuncionalidade();
    private DataModel gridFuncionalidades;
    private int idFuncionalidadeMae;
    private boolean isTitulo;

    
    private List<TbFuncionalidade> listaFuncionalidades = new ArrayList<TbFuncionalidade>();
   

    public FuncionalidadeController(){
        this.consultaListaFuncionalidades();
    }

    public TbFuncionalidade getInserirFuncionalidade() {
        return inserirFuncionalidade;
    }

    public void setInserirFuncionalidade(TbFuncionalidade inserirFuncionalidade) {
        this.inserirFuncionalidade = inserirFuncionalidade;
    }

    public DataModel getGridFuncionalidade() {
        return gridFuncionalidades;
    }

    public void setGridFuncionalidade(DataModel gridFuncionalidades) {
        this.gridFuncionalidades = gridFuncionalidades;
    }

    public int getIdFuncionalidadeMae() {
        return idFuncionalidadeMae;
    }

    public void setIdFuncionalidadeMae(int idFuncionalidadePai) {
        this.idFuncionalidadeMae = idFuncionalidadePai;
    }

    public boolean isIsTitulo() {
        return isTitulo;
    }

    public void setIsTitulo(boolean isTitulo) {
        this.isTitulo = isTitulo;
    }
    
    
    
    
    public String insereFuncionalidade(){
        FuncionalidadeService ps = new FuncionalidadeServiceImpl();
        this.getInserirFuncionalidade().setIdFuncionalidade(this.getIdFuncionalidadeMae());
        TbFuncionalidade Funcionalidade = ps.inserir(this.getInserirFuncionalidade());
        this.setMensagem("Erro ao inserir funcionalidade.");
        if(Funcionalidade!=null){
            this.setMensagem("Funcionalidade inserida com sucesso.");
        }
        this.consultaListaFuncionalidades();
        this.inserirFuncionalidade =new TbFuncionalidade();
        return "/view/admin/cadastro/funcionalidade.xhtml";
    }
     
    public List<TbFuncionalidade> getListaFuncionalidade() {
        this.consultaListaFuncionalidades();
        return listaFuncionalidades;
    }

    public void setListaFuncionalidade(List<TbFuncionalidade> Funcionalidade) {
        this.listaFuncionalidades = Funcionalidade;
    }


    public String prepararAlterar(){
        TbFuncionalidade genCategoria = (TbFuncionalidade) this.gridFuncionalidades.getRowData();
        this.inserirFuncionalidade=genCategoria;
        return "/view/admin/altera/funcionalidade.xhtml";
    }

    public String apaga(){

        FuncionalidadeService ps=new FuncionalidadeServiceImpl();
        TbFuncionalidade Funcionalidade = (TbFuncionalidade) this.gridFuncionalidades.getRowData();
        ps.apagar(Funcionalidade);
        this.consultaListaFuncionalidades();
        return "/view/admin/cadastro/funcionalidade.xhtml";
    }

    public String gravaAlteracao(){
        FuncionalidadeService ps=new FuncionalidadeServiceImpl();
        ps.atualizar(this.inserirFuncionalidade);
        this.consultaListaFuncionalidades();
        this.setMensagem("Funcionalidade alterada com sucesso.");
        this.inserirFuncionalidade = new TbFuncionalidade();
        return "/view/admin/cadastro/funcionalidade.xhtml";
    }
    
    private void consultaListaFuncionalidades(){
        FuncionalidadeService ps=new FuncionalidadeServiceImpl();
        this.listaFuncionalidades = ps.pesquisarTodos();
        this.gridFuncionalidades = new ListDataModel(this.listaFuncionalidades);
    }
}

src/java/controller/PerfilFuncionalidadeController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import model.TbFuncionalidade;
import model.TbPerfil;
import model.TbPerfilFuncionalidade;
import model.TbPerfilFuncionalidadePK;
import model.VwPerfilFuncionalidade;
import service.PerfilFuncionalidadeService;
import service.VwPerfilFuncionalidadeService;
import service.impl.PerfilFuncionalidadeServiceImpl;
import service.impl.VwPerfilFuncionalidadeServiceImpl;

/**
 *
 * @author KAMYLLA
 */
@ManagedBean(name = "PerfilFuncionalidade")
@SessionScoped
public class PerfilFuncionalidadeController extends BasicController {

    private TbPerfilFuncionalidade inserirPerfilFuncionalidade = new TbPerfilFuncionalidade();
    private DataModel gridPerfilFuncionalidades;
    private int idPerfil, idFuncionalidade;
    private List<VwPerfilFuncionalidade> listaPerfilFuncionalidades = new ArrayList<VwPerfilFuncionalidade>();

    public PerfilFuncionalidadeController() {
        this.consultaListaPerfilFuncionalidades();
    }

    public TbPerfilFuncionalidade getInserirPerfilFuncionalidade() {
        return inserirPerfilFuncionalidade;
    }

    public void setInserirPerfilFuncionalidade(TbPerfilFuncionalidade inserirPerfilFuncionalidade) {
        this.inserirPerfilFuncionalidade = inserirPerfilFuncionalidade;
    }

    public DataModel getGridPerfilFuncionalidade() {
        return gridPerfilFuncionalidades;
    }

    public void setGridPerfilFuncionalidade(DataModel gridPerfilFuncionalidades) {
        this.gridPerfilFuncionalidades = gridPerfilFuncionalidades;
    }

    public int getIdFuncionalidade() {
        return idFuncionalidade;
    }

    public void setIdFuncionalidade(int idFuncionalidade) {
        this.idFuncionalidade = idFuncionalidade;
    }

    public int getIdPerfil() {
        return idPerfil;
    }

    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    

    public String inserePerfilFuncionalidade() {
        PerfilFuncionalidadeService ps = new PerfilFuncionalidadeServiceImpl();
        this.getInserirPerfilFuncionalidade().setTbPerfil(new TbPerfil(this.getIdPerfil()));
        this.getInserirPerfilFuncionalidade().setTbFuncionalidade(new TbFuncionalidade(this.getIdFuncionalidade()));
        this.getInserirPerfilFuncionalidade().setTbPerfilFuncionalidadePK(new TbPerfilFuncionalidadePK(this.getIdPerfil(), this.getIdFuncionalidade()));
        
        TbPerfilFuncionalidade perfilFunc = ps.pesquisarPorPerfilEFuncionalidade(this.idPerfil, this.idFuncionalidade);
        if(perfilFunc != null){
            this.setMensagem("Funcionalidade do Perfil já existente. ");
            return "/view/admin/cadastro/perfilFuncionalidade.xhtml";
        }
        
        TbPerfilFuncionalidade PerfilFuncionalidade = ps.inserir(this.getInserirPerfilFuncionalidade());
        this.setMensagem("Erro ao inserir Funcionalidade do Perfil.");
        
        if (PerfilFuncionalidade != null) {
            this.setMensagem("Funcionalidade do Perfil inserido com sucesso.");
        }
        this.inserirPerfilFuncionalidade = new TbPerfilFuncionalidade();
        this.consultaListaPerfilFuncionalidades();
        return "/view/admin/cadastro/perfilFuncionalidade.xhtml";
    }

    public List<VwPerfilFuncionalidade> getListaPerfilFuncionalidade() {
        this.consultaListaPerfilFuncionalidades();
        return listaPerfilFuncionalidades;
    }

    public void setListaPerfilFuncionalidade(List<VwPerfilFuncionalidade> PerfilFuncionalidade) {
        this.listaPerfilFuncionalidades = PerfilFuncionalidade;
    }

    public String prepararAlterar() {
        TbPerfilFuncionalidade genCategoria = (TbPerfilFuncionalidade) this.gridPerfilFuncionalidades.getRowData();
        this.inserirPerfilFuncionalidade = genCategoria;
        return "/view/admin/altera/perfilFuncionalidade.xhtml";
    }

    public String apagaPerfilFuncionalidade() {


        PerfilFuncionalidadeService ps = new PerfilFuncionalidadeServiceImpl();

        VwPerfilFuncionalidade selecionada = (VwPerfilFuncionalidade) this.gridPerfilFuncionalidades.getRowData();
        TbPerfilFuncionalidade nova = new TbPerfilFuncionalidade();

        if (selecionada != null) {
            int a=0;
            if(selecionada.getIdPerfil()!=null)a = selecionada.getIdPerfil().intValue();
            int b=0;
            if(selecionada.getIdFuncionalidade()!=null)b = selecionada.getIdFuncionalidade().intValue();
            
            nova = ps.pesquisarPorPerfilEFuncionalidade(a,b);
            if (nova != null) {
                ps.apagar(nova);
            }
        }
        this.consultaListaPerfilFuncionalidades();
        
        return "/view/admin/cadastro/perfilFuncionalidade.xhtml";
        
        
    }

    public String gravaAlteracao() {
        PerfilFuncionalidadeService ps = new PerfilFuncionalidadeServiceImpl();
        ps.atualizar(this.inserirPerfilFuncionalidade);
        this.consultaListaPerfilFuncionalidades();
        this.setMensagem("Perfil da Funcionalidade alterada com sucesso.");
        this.inserirPerfilFuncionalidade = new TbPerfilFuncionalidade();
        consultaListaPerfilFuncionalidades();
        return "/view/admin/cadastro/perfilFuncionalidade.xhtml";
    }

    private void consultaListaPerfilFuncionalidades() {
        VwPerfilFuncionalidadeService vpf = new VwPerfilFuncionalidadeServiceImpl();
        this.listaPerfilFuncionalidades = vpf.pesquisarTodosOrdenado();
        this.gridPerfilFuncionalidades = new ListDataModel(this.listaPerfilFuncionalidades);
    }
}

web/operation/admin/listagem/categoria.xhtml
<h:panelGroup xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:ui="http://java.sun.com/jsf/facelets" 
              xmlns:f="http://java.sun.com/jsf/core" >
    <h:panelGrid columns="1">
        <h:outputLabel styleClass="lblBoldAzul" value="Categorias Cadastradas:"/>
    </h:panelGrid>
    <h:panelGrid columns="1">
        <h:dataTable value="#{Categoria.gridCategorias}" var="atual" border="0" cellpadding="10" cellspacing="10" rowClasses="linhasimpares, linhaspares" headerClass="TituloTabelaVariavel" columnClasses="TituloTabela1"  >
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Categoria:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmCategoria}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Alterar: "/></f:facet>
                <h:commandLink value="Alterar" action="#{Categoria.prepararAlterar}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Excluir Categoria: "/></f:facet>
                <h:commandLink value="Excluir" action="#{Categoria.excluirCategoria}"  onclick="return confirm('Deseja excluir a categoria #{atual.nmCategoria} ?');" />
            </h:column>
        </h:dataTable>
    </h:panelGrid>
</h:panelGroup>

web/operation/admin/listagem/categoriaCriterio.xhtml
<h:panelGroup xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:ui="http://java.sun.com/jsf/facelets" 
              xmlns:f="http://java.sun.com/jsf/core" >
    <h:panelGrid columns="1">
        <h:outputLabel styleClass="lblBoldAzul" value="Categorias dos Critérios Cadastrados:"/>
    </h:panelGrid>
    <h:panelGrid columns="1">
        <h:dataTable value="#{CategoriaCriterio.gridCategoriaCriterios}" var="atual" border="0" cellpadding="10" cellspacing="10" rowClasses="linhasimpares, linhaspares" headerClass="TituloTabelaVariavel" columnClasses="TituloTabela1"  >
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Categoria do Critério:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmCategoriaCriterio}"/>
            </h:column>
             <h:column>
                <f:facet name="header"><h:outputLabel  value="Valor Máximo:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nrValorMaximo}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Alterar: "/></f:facet>
                <h:commandLink value="Alterar" action="#{CategoriaCriterio.prepararAlterar}"/>
            </h:column>
            <!--<h:column>
                <f:facet name="header"><h:outputLabel value="Excluir : "/></f:facet>
                <h:commandLink value="Excluir" action="#{CategoriaCriterio.apaga}"  onclick="return confirm('Deseja excluir a categoria do critério #{atual.nmCategoriaCriterio} ?');" />
            </h:column>-->
        </h:dataTable>
    </h:panelGrid>
</h:panelGroup>

web/operation/admin/listagem/colaboradorBanca.xhtml
<h:panelGroup xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:ui="http://java.sun.com/jsf/facelets" 
              xmlns:f="http://java.sun.com/jsf/core" 
              xmlns:p="http://primefaces.prime.com.tr/ui">
   
  
    
   
    <h:panelGrid columns="1" id="pnlListaColaboradores" >
       
   <h:dataTable id="tblDadosColaboradores" value="#{Colaborador.gridColaboradorBanca}" var="atual" border="0" cellpadding="10" cellspacing="10" rowClasses="linhasimpares, linhaspares" headerClass="TituloTabelaVariavel" columnClasses="TituloTabela1"  >
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Colaborador"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmPessoa}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Processo"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmProcesso}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Banca"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmBanca}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Função"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmFuncao}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Tipo de Correção"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmTipoCorrecao}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Número da Questão"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmQuestao}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Banca "/></f:facet>
                <h:selectOneMenu  value="#{atual.idBanca}">
                    <f:selectItem itemLabel="--- Nenhuma ---" itemValue="0"/>
                    <f:selectItems value="#{Banca.listaBanca}" var="cboItensBanca" itemValue="#{cboItensBanca.idBanca}" itemLabel="#{cboItensBanca.nmBanca}"/>
                    <f:ajax listener="#{Colaborador.selecionaBanca()}" event="click" execute="@this" />
                </h:selectOneMenu>
            </h:column>
            
            
        </h:dataTable>
    </h:panelGrid>
</h:panelGroup>

web/operation/admin/listagem/funcionalidade.xhtml
<h:panelGroup xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:ui="http://java.sun.com/jsf/facelets" 
              xmlns:f="http://java.sun.com/jsf/core" >
    <h:panelGrid columns="1">
        <h:outputLabel styleClass="lblBoldAzul" value="Funcionalidades Cadastradas:"/>
    </h:panelGrid>
    <h:panelGrid columns="1">
        <h:dataTable value="#{Funcionalidade.gridFuncionalidade}" var="atual" border="0" cellpadding="10" cellspacing="10" rowClasses="linhasimpares, linhaspares" headerClass="TituloTabelaVariavel" columnClasses="TituloTabela1"  >
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Nome do Funcionalidade:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmFuncionalidade}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Alterar: "/></f:facet>
                <h:commandLink value="Alterar" action="#{Funcionalidade.prepararAlterar}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Excluir: "/></f:facet>
                <h:commandLink value="Excluir" action="#{Funcionalidade.apaga()}"  onclick="return confirm('Deseja excluir a Funcionalidade #{atual.nmFuncionalidade} ?');" />
            </h:column>
        </h:dataTable>
    </h:panelGrid>
</h:panelGroup>

web/operation/admin/listagem/perfilFuncionalidade.xhtml
<h:panelGroup xmlns="http://www.w3.org/1999/xhtml"
              xmlns:h="http://java.sun.com/jsf/html"
              xmlns:ui="http://java.sun.com/jsf/facelets" 
              xmlns:f="http://java.sun.com/jsf/core" >
    <h:panelGrid columns="1">
        <h:outputLabel styleClass="lblBoldAzul" value="Funcionalidades dos Perfis Cadastrados:"/>
    </h:panelGrid>
    <h:panelGrid columns="1">
        <h:dataTable value="#{PerfilFuncionalidade.gridPerfilFuncionalidade}" var="atual" border="0" cellpadding="10" cellspacing="10" rowClasses="linhasimpares, linhaspares" headerClass="TituloTabelaVariavel" columnClasses="TituloTabela1"  >
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Perfil:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmPerfil}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Funcionalidade"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nmFuncionalidade}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel  value="Ordem:"/></f:facet>
                <h:outputLabel styleClass="digita" value="#{atual.nrOrdem}"/>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputLabel value="Excluir: "/></f:facet>
                <h:commandLink value="Excluir" action="#{PerfilFuncionalidade.apagaPerfilFuncionalidade()}"  onclick="return confirm('Deseja excluir a funcionalidade para o perfil #{atual.nmPerfil} ?');" />
            </h:column>
        </h:dataTable>
    </h:panelGrid>
</h:panelGroup>